"""Exercise actual 2v2 DOM, workers, renderer and saved-state workflow.
Document injection is needed under the managed browser's URL policy.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,time,hashlib,traceback,os
R=Path(__file__).resolve().parents[1];results=[];errors=[];requests=[];measurements={};start=time.time();skipped=[]
def check(name,ok,detail=None):
 results.append({'name':name,'pass':bool(ok),**({'detail':detail} if detail is not None else {})});print(('PASS ' if ok else 'FAIL ')+name,flush=True)
def save():
 (R/'reports/doubles-browser-tests.json').write_text(json.dumps({'htmlSha256':hashlib.sha256((R/'index.html').read_bytes()).hexdigest(),'passed':sum(x['pass'] for x in results),'failed':sum(not x['pass'] for x in results),'results':results,'skipped':skipped,'measurements':measurements,'errors':errors,'seconds':time.time()-start,'limitations':['Document injection: file/HTTP URL navigation is blocked in this test browser. Real-origin autosave reload not verified.','Canvas is tested directly; see skipped for WebGL availability. No native gaming-GPU benchmark.']},indent=2))
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH'),headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
 page=b.new_page(viewport={'width':1440,'height':900},accept_downloads=True);page.set_default_timeout(14000)
 page.on('pageerror',lambda e:errors.append(e.stack if hasattr(e,'stack') else str(e)));page.on('request',lambda r:requests.append(r.url) if r.url.startswith(('http:','https:')) else None)
 def ev(s,arg=None):return page.evaluate(s,arg)
 def req(t,**kw):return ev('(m)=>app.request(m.type,m.args)',{'type':t,'args':kw})
 try:
  page.set_content((R/'index.html').read_text(),wait_until='domcontentloaded');page.wait_for_function('app?.ready');page.wait_for_timeout(1500)
  check('Single-file release starts without external network assets',not requests)
  check('1v1 remains the default with its original two-player roster',ev('app.b.cars.length===2&&app.telemetry.mode==="duel"'))
  check('Two visible format buttons expose selected state',page.is_visible('[data-match="doubles"]') and page.get_attribute('[data-match="duel"]','aria-pressed')=='true')
  check('Additional agent cameras are hidden in 1v1',not page.is_visible('[data-view="slate"]') and not page.is_visible('[data-view="sienna"]'))
  page.click('[data-match="doubles"]');page.wait_for_function('app.b.cars.length===4');page.wait_for_timeout(900)
  check('Clicking 2v2 changes the real worker roster',ev('app.telemetry.agents.length===4&&app.telemetry.mode==="doubles"'))
  check('2v2 selection is reflected in the format buttons and settings',ev('mode.value==="doubles"&&document.querySelector("[data-match=doubles]").getAttribute("aria-pressed")==="true"'))
  check('2v2 shows team score labels, not two individual-player scores',page.inner_text('#team0')=='BLUE' and page.inner_text('#team1')=='ORANGE')
  check('Extra camera buttons are available for both new agents',page.is_visible('[data-view="slate"]') and page.is_visible('[data-view="sienna"]'))
  check('Both renderers have distinct models for all four cars',ev('app.renderer.carBodies.length===4'))
  page.wait_for_timeout(4000)
  check('All four policies update during ordinary real-time play',ev('app.telemetry.updates.every(n=>n>2)&&app.telemetry.norms.every(n=>n>0)'))
  check('Four-player simulation stays in its own worker',ev('!!app.worker&&!app.fallback'))
  req('pause',value=True);page.wait_for_timeout(350);before=req('export');page.wait_for_timeout(450)
  check('Pause freezes all four learners and the physical world',req('export')['universe']==before['universe'])
  check('Portable export identifies the four-player format',before['format']=='touchline-world-v11' and len(before['universe']['brains'])==4)
  check('Existing Atelier interface remains flat, not skeuomorphic',ev('getComputedStyle(document.querySelector(".scoreboard")).boxShadow==="none"'))
  for view,idx in [('mica',0),('ember',1),('slate',2),('sienna',3)]:
   page.click('[data-view="'+view+'"]');page.wait_for_timeout(300)
   check(view.title()+' follow camera selects a valid distinct player',ev('(v)=>app.renderer.mode===v',view) and view.upper() in page.inner_text('#viewName'))
  check('Follow background cache includes the full field, avoiding clipped borders',ev('app.renderer.cacheSize>app.renderer.cameraSize'))
  ev('app.view("arena");app.selectAgent(2);app.openInspector(true);app.setTab("now")');page.wait_for_timeout(450)
  check('Fieldnotes offers all four agent tabs',page.locator('[data-agent]:visible').count()==4)
  check('Slate has a separate portrait and learned-state readout',page.inner_text('#portraitName')=='Slate' and ev('app.agent===2'))
  check('Team readout identifies Slate as blue, not orange',page.is_visible('#teamReadout') and page.inner_text('#teamReadout').startswith('BLUE'))
  page.click('[data-agent="3"]');page.wait_for_timeout(300)
  check('Sienna has a separate portrait and orange-team context',page.inner_text('#portraitName')=='Sienna' and page.inner_text('#teamReadout').startswith('ORANGE'))
  check('Team readout reports actual received-pass and assist counters','received passes' in page.inner_text('#teamReadout') and 'assists' in page.inner_text('#teamReadout'))
  page.click('#followAgent');page.wait_for_timeout(200)
  check('Follow selected agent follows Sienna, not Ember',ev('app.renderer.mode==="sienna"&&!app.drawer'))
  page.keyboard.press('5');check('Keyboard 5 follows Slate',ev('app.renderer.mode==="slate"'))
  page.keyboard.press('6');check('Keyboard 6 follows Sienna',ev('app.renderer.mode==="sienna"'))
  # Actual timeline fast-forward, not a fabricated discovery.
  req('testAdvance',testing=True,steps=10800);page.wait_for_timeout(600)
  check('Observer records sequences for the added agents',ev('app.detail.patterns.some(p=>p.agent===2)&&app.detail.patterns.some(p=>p.agent===3)'))
  check('Every reported learned parameter is finite',ev('app.detail.agents.every(a=>a.weights.length===64&&a.weights.every(Number.isFinite))'))
  exported=req('export');measurements['exportBytes']=len(json.dumps(exported));req('import',data=exported);page.wait_for_timeout(350)
  check('2v2 full-state import restores all physical players',len(req('export')['universe']['dynamics']['cars'])==4)
  check('All four learned policies survive full-state import',req('export')['policies']==exported['policies'])
  ev('app.setTab("discoveries");app.openInspector(true)');page.wait_for_timeout(250)
  check('Discovery entries safely label Slate and Sienna','SLATE' in page.inner_text('#discoveries') and 'SIENNA' in page.inner_text('#discoveries'))
  ev('app.startReplay(app.detail.patterns.find(p=>p.agent===2&&p.clipAvailable))');page.wait_for_function('!!app.replay');page.wait_for_timeout(250)
  check('Recorded sequence contains all four physical agents',ev('app.replay.frames.every(f=>f.cars.length===4)'))
  ev('app.selectAgent(2);app.setTab("now");app.openInspector(true)');page.wait_for_timeout(250)
  check('Replay does not show current team plans as historical evidence',not page.is_visible('#teamReadout') and 'Recorded' in page.inner_text('#intent'))
  ev('app.openInspector(false);app.stopReplay()');page.wait_for_timeout(200)
  check('Returning live restores four-player scene',ev('!app.replay&&app.b.cars.length===4'))
  old=req('export')['policies'];page.click('[data-match="duel"]');page.wait_for_function('app.b.cars.length===2');page.wait_for_timeout(350)
  check('Switching back removes additional physics bodies and brains',len(req('export')['universe']['brains'])==2)
  check('Removed-player selection and follow camera fall back safely',ev('app.agent<2&&!['+'"slate","sienna"'+'].includes(app.renderer.mode)'))
  check('Additional player controls are hidden again',not page.is_visible('[data-view="slate"]'))
  page.click('[data-match="doubles"]');page.wait_for_function('app.b.cars.length===4');page.wait_for_timeout(250)
  check('Returning to 2v2 keeps its four distinct learned policies',req('export')['policies']==old)
  req('human',value=True);req('testAdvance',testing=True,steps=1200)
  check('Player can take over Mica without removing other three agents',ev('app.telemetry.human===0&&app.telemetry.agents.length===4'))
  req('human',value=False);req('learning',value=False);saved=req('export')['policies'];req('testAdvance',testing=True,steps=600)
  check('Learning switch freezes all four policies while physics runs',[x['w'] for x in req('export')['policies']]==[x['w'] for x in saved]);req('learning',value=True)
  arc=req('archive');req('spar',value=arc['id']);check('Historical team mode freezes both orange agents',ev('app.telemetry.agents[1].frozen&&app.telemetry.agents[3].frozen&&!app.telemetry.agents[2].frozen'));req('spar',value='live')
  ev('app.setTab("lab");app.openInspector(true)');page.wait_for_timeout(350)
  check('Historical team comparison is enabled in 2v2',not page.is_disabled('#evaluate'))
  check('History control describes the whole orange team',page.text_content('#sparLabel')=='Orange team policies')
  ev('app.openInspector(false);app.view("arena")');req('weather',value={'mode':'rain','hour':22});req('testAdvance',testing=True,steps=1800);page.wait_for_timeout(500)
  check('Rain and nighttime work with all four agents',ev('app.telemetry.weather.rain>0&&app.b.cars.length===4'))
  req('intervene',kind='sphere',x=6,z=2);check('Heavy-ball interventions coexist with four players',ev('app.b.props.length>0'))
  req('life',value=True);req('lifeMode',value='ecology');req('testAdvance',testing=True,steps=600);check('Living surface still operates in team matches',ev('app.telemetry.life&&app.telemetry.lifeMode==="ecology"'))
  # Responsive layouts and keyboard accessibility, measured from actual rectangles.
  for width,height,label in [(1440,900,'desktop'),(1024,768,'tablet'),(390,844,'mobile'),(360,780,'compact mobile'),(900,500,'landscape')]:
   page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(650)
   layout=ev('''()=>{const ids=['stage','formatSwitch','dock','cameraChapters'];return Object.fromEntries(ids.map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return [id,{visible:!!e.getClientRects().length&&getComputedStyle(e).display!=='none',x:r.x,y:r.y,w:r.width,h:r.height}]}));}''')
   check(label+' has no horizontal document overflow',ev('document.documentElement.scrollWidth<=innerWidth'))
   switch=layout['formatSwitch'];check(label+' keeps the match switch in the viewport',switch['visible'] and switch['x']>=0 and switch['x']+switch['w']<=width+1)
   check(label+' has usable camera controls',page.is_visible('#cameraChapters') or page.is_visible('#camera'))
   if label=='mobile':
    page.screenshot(path=str(R/'previews/doubles-mobile.png'))
    page.click('#inspectButton');page.wait_for_timeout(200);check('Mobile inspector correctly makes the arena inert',ev('game.inert&&inspector.getAttribute("aria-modal")==="true"'))
    ev('app.setTab("now");app.selectAgent(3)');page.wait_for_timeout(200);check('Mobile inspector shows and selects Sienna',page.inner_text('#portraitName')=='Sienna')
    page.focus('#closeInspector');page.keyboard.press('Shift+Tab');check('Mobile keyboard focus stays inside Fieldnotes',ev('inspector.contains(document.activeElement)'))
    page.keyboard.press('Escape');page.wait_for_timeout(200);check('Escape restores interactive arena controls',ev('!app.drawer&&!game.inert'))
  page.set_viewport_size({'width':1440,'height':900});page.wait_for_timeout(300)
  req('reset');check('Reset clears every 2v2 learner, not only Mica and Ember',ev('app.telemetry.updates.every(n=>n===0)&&app.telemetry.norms.every(n=>n===0)'))
  check('Reset keeps the four-player format and systemic world',ev('app.telemetry.mode==="doubles"&&app.telemetry.weather.rain>0'))
  check('No uncaught page errors across all team workflows',not errors,errors)
 except Exception as e:check('Browser suite completed',False,traceback.format_exc())
 finally:save();b.close()
# Explicit software-GPU shader validation, separate from the live-performance run.
with sync_playwright() as p:
 try:
  b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH'),headless=True,args=['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'])
  page=b.new_page(viewport={'width':1200,'height':800});page.evaluate('window.touchlineGraphics="webgl"');page.set_content((R/'index.html').read_text(),wait_until='domcontentloaded');page.wait_for_function('app?.ready');page.evaluate('app.switchGraphics("webgl")');page.wait_for_timeout(600)
  page.evaluate('app.changeMatch("doubles")');page.wait_for_function('app.b.cars.length===4');page.wait_for_timeout(1200)
  gl=page.evaluate('''()=>({kind:app.renderer.kind,gl:!!app.renderer.gl,error:app.renderer.gl?.getError(),models:app.renderer.carBodies?.length,cars:app.b.cars.length})''');measurements['webgl']=gl
  supported=page.evaluate('!!document.createElement("canvas").getContext("webgl2")')
  if supported:
   check('WebGL2 renders all four meshes without a shader or uniform error',gl.get('gl') and gl.get('error')==0 and gl.get('models')==4,gl)
  else:
   skipped.append({'name':'Actual WebGL rendering and GPU-context-loss tests','reason':'The test host returns null for a bare WebGL2 context, including explicit SwiftShader. GPU rendering is unverified in this run.'})
   check('Unavailable WebGL falls back without removing team members',not gl.get('gl') and gl.get('models')==4 and gl.get('cars')==4,gl)
   snap=page.evaluate('app.request("pause",{value:true}).then(()=>app.request("export"))')
   page.evaluate('app.switchGraphics("canvas")');page.wait_for_timeout(300)
   check('Explicit lightweight recovery preserves all four policies and physics',page.evaluate('app.request("export")')['universe']==snap['universe'])
  if gl.get('gl'):
   page.evaluate('app.renderer.gl.getExtension("WEBGL_lose_context").loseContext()');page.wait_for_timeout(800)
   check('Graphics-context loss preserves the live four-player world',page.evaluate('!!app.renderer.fallback&&app.b.cars.length===4&&app.telemetry.updates.every(n=>n>0)'))
  b.close()
 except Exception:check('Explicit WebGL path available for testing',False,traceback.format_exc())
 finally:save()
raise SystemExit(1 if any(not x['pass'] for x in results) else 0)
