"""Exercise the built cartridge in Chromium; no screenshot or simulation mocks.
Managed-browser policy blocks file/HTTP navigation here, so the document is injected.
Consequently persistence on a non-opaque origin is not covered by this suite.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,time,statistics,traceback,os,shutil,hashlib
R=Path(__file__).resolve().parents[1]
results=[];errors=[];requests=[];measurements={};started=time.time()
def check(name,ok,detail=None):
 r={'name':name,'pass':bool(ok)}
 if detail is not None:r['detail']=detail
 results.append(r);print(str(round(time.time()-started,1))+'s '+('PASS ' if ok else 'FAIL ')+name,flush=True);save_report()
def save_report():
 report={'sourceSha256':hashlib.sha256((R/'index.html').read_bytes()).hexdigest(),'date':time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime()),'passed':sum(x['pass'] for x in results),'failed':sum(not x['pass'] for x in results),'results':results,'errors':errors,'measurements':measurements,'durationSeconds':round(time.time()-started,1),'limitations':['Headless Chromium on the test host, not a gaming-GPU or user-laptop benchmark.','Document injection used: enterprise policy blocks file and HTTP URL navigation. Real-origin IndexedDB save/reload is not verified.','Fast-forward is used for history/replay coverage; performance samples use ordinary live playback.']}
 (R/'reports/world-browser-tests.json').write_text(json.dumps(report,indent=2))
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH'),headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
 ctx=b.new_context(viewport={'width':1440,'height':900},accept_downloads=True)
 page=ctx.new_page();page.set_default_timeout(10000)
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url) if r.url.startswith(('http://','https://')) else None)
 def ev(s,arg=None):return page.evaluate(s,arg)
 def req(t,**kw):return ev('(m)=>app.request(m.type,m.args)',{'type':t,'args':kw})
 def fold(text):
  el=page.locator('details').filter(has=page.locator('summary',has_text=text)).first
  if el.get_attribute('open') is None:el.locator('summary').click()
 def pause():req('pause',value=True);page.wait_for_timeout(200)
 def advance(n):return req('testAdvance',testing=True,steps=n)
 def quiet():page.wait_for_function('!document.getElementById("goal").classList.contains("show")&&!document.getElementById("notice").classList.contains("show")',timeout=20000)
 def worldtab():
  ev('app.setTab("lab");app.openInspector(true)');page.wait_for_timeout(250)
 def perf():return ev('({fps:app.fps,renderMs:app.renderer.renderMs,workerTickMs:app.telemetry.tickMs,actualPace:app.telemetry.pace,backing:[app.renderer.w,app.renderer.h],longTasks:app.debug.longTasks.slice(-10)})')
 try:
  page.set_content((R/'index.html').read_text(),wait_until='domcontentloaded')
  page.wait_for_function('window.touchlineReady===true',timeout=15000);page.wait_for_timeout(6500)
  check('Standalone document starts without external asset requests',not requests)
  check('Live physics and learning run in a dedicated worker',ev('!!app.worker&&app.workerMode==="Dedicated worker"'))
  check('Both models update in ordinary real-time play',ev('app.telemetry.updates.every(n=>n>2)&&app.telemetry.norms.every(n=>n>0)'))
  check('Default view hides all inspector panels',not page.is_visible('#inspector'))
  check('Default interface contains a live weather clock',page.is_visible('#weatherBadge') and bool(page.inner_text('#worldClock')))
  measurements['desktopDaylight']=perf()
  check('Live simulation keeps near real-time pace',.8<measurements['desktopDaylight']['actualPace']<1.2,measurements['desktopDaylight'])
  check('Presentation exceeds 45 fps in the desktop daylight sample',measurements['desktopDaylight']['fps']>45)
  pause();quiet();page.screenshot(path=str(R/'previews/daylight.png'))
  page.click('#weatherBadge');check('Weather badge opens the World instruments',page.is_visible('#panel-lab'))
  page.select_option('#weatherMode','rain');page.wait_for_function('app.telemetry.weather.mode==="rain"')
  before=req('export');advance(7200);after=req('export')
  check('Rain front actually increases atmospheric rain and turf moisture',after['universe']['weather']['rain']>before['universe']['weather']['rain']+.3 and sum(after['universe']['field']['wet'])>sum(before['universe']['field']['wet'])+100)
  check('Weather-aware learner exposes 64 coefficients',all(len(x['w'])==64 for x in after['universe']['brains']))
  check('Both learned models continue changing in wet conditions',all(after['universe']['brains'][i]['w']!=before['universe']['brains'][i]['w'] for i in (0,1)))
  page.select_option('#dayLength','1200');check('Day-cycle duration is an actual simulation parameter',req('export')['universe']['weather']['dayLength']==1200)
  page.click('[data-hour="22"]');page.wait_for_function('app.renderer.theme==="night"')
  check('Night preset changes the actual world clock',abs(req('export')['universe']['weather']['clock']-22/24)<.001)
  quiet();page.screenshot(path=str(R/'previews/weather-panel.png'));page.click('#closeInspector');page.screenshot(path=str(R/'previews/rain-night.png'))
  req('pause',value=False);page.wait_for_timeout(5200);measurements['desktopRainNight']=perf()
  check('Live night rain maintains simulation pace',.8<measurements['desktopRainNight']['actualPace']<1.2,measurements['desktopRainNight'])
  page.click('[data-view="mica"]');page.wait_for_timeout(5000);measurements['desktopFollowRain']=perf()
  check('Follow camera uses the same independent live world',ev('app.renderer.mode==="mica"&&app.telemetry.updates.every(n=>n>20)'))
  pause();quiet();page.screenshot(path=str(R/'previews/follow.png'));page.click('[data-view="arena"]')
  page.click('#inspectButton');page.click('#tab-now');page.wait_for_timeout(500)
  check('Agent inspector shows route moisture and actual approach controls','Route' in page.inner_text('#planReadout') and 'Engine heat' in page.inner_text('#planReadout'))
  fold('Compared plans');check('Compared plans expose authored prior and learned residual',page.locator('#alternatives .plan-option').count()>1 and 'learned' in page.inner_text('#alternatives'))
  page.click('[data-agent="1"]');check('Other learner has its own inspector',ev('app.agent===1'))
  page.click('[data-agent="0"]');page.screenshot(path=str(R/'previews/agent.png'))
  page.click('#tab-discoveries');page.wait_for_timeout(250)
  check('Discovery cards are generated from actual opportunities',page.locator('.entry').count()>0)
  check('Failed opportunities are retained in the live journal',ev('app.detail.patterns.some(p=>p.misses>0)'))
  check('Sequences are compared within environmental contexts',ev('app.detail.patterns.some(p=>p.context.includes("wet")||p.context.includes("damp"))'))
  check('Inspector does not announce unsupported invention','proof of invention' in page.content() and 'CANDIDATE' in page.inner_text('#discoveries'))
  page.screenshot(path=str(R/'previews/discoveries.png'))
  page.locator('.entry button:not([disabled])').first.click();page.wait_for_function('!!app.replay')
  r0=ev('({time:app.b.time,updates:app.telemetry.updates})');page.wait_for_timeout(500)
  check('Replay pauses live training instead of training on recorded data',r0==ev('({time:app.b.time,updates:app.telemetry.updates})'))
  check('Replay carries recorded atmosphere and surface data',ev('app.replay.frames.length>10&&app.replay.frames.every(f=>f.weather&&f.surface&&f.cars.length===2)'))
  page.click('#ribbonExit');check('Replay returns to the retained live world',ev('!app.replay'))
  worldtab();fold('History & comparisons')
  page.click('#archiveNow');page.wait_for_timeout(300)
  check('Manual historical snapshot adds real policies',ev('app.detail.archives.length>=2'))
  baseline=page.locator('#archiveSelect option').first.get_attribute('value');page.select_option('#sparSelect',baseline);page.wait_for_function('!!app.telemetry.bench')
  frozen=req('export');advance(1200);later=req('export')
  check('Archived Ember is frozen while Mica remains a learner',later['universe']['brains'][1]['w']==frozen['universe']['brains'][1]['w'] and later['universe']['brains'][0]['w']!=frozen['universe']['brains'][0]['w'])
  check('Archived opponent is clearly disclosed',ev('app.telemetry.agents[1].frozen'))
  page.select_option('#mode','coop');page.wait_for_timeout(250)
  check('Mode-switch rejection while sparring is handled without crashing',ev('app.telemetry.mode==="duel"&&document.getElementById("mode").value==="duel"'))
  page.select_option('#sparSelect','live');page.wait_for_function('!app.telemetry.bench')
  check('Original live Ember policy is restored intact',req('export')['universe']['brains'][1]['w']==frozen['bench']['policies']['1']['w'])
  page.select_option('#archiveSelect',baseline);req('pause',value=False)
  live0=ev('app.telemetry.updates');page.click('#evaluate');page.wait_for_function('!!app.job')
  check('Historical evaluation runs in another worker',ev('app.job.worker instanceof Worker&&app.job.worker!==app.worker'))
  page.wait_for_function('!app.job&&document.getElementById("evaluationReport").textContent.includes("matched starts")',timeout=30000,polling=100)
  pause();eval_result=req('export')['evaluations'][-1];measurements['historicalEvaluation']=eval_result
  check('Evaluation completes all 16 frozen games',eval_result['gameCount']==16 and len(eval_result['rows'])==8 and eval_result['frozen'])
  check('Live learners continue updating during the separate comparison',all(a>b for a,b in zip(ev('app.telemetry.updates'),live0)))
  check('Comparison result states the sample it was measured over','s per game' in page.inner_text('#evaluationReport') and 'swapped sides' in page.inner_text('#evaluationReport'))
  check('Evaluation report persists inside full-world exports',len(req('export')['evaluations'])>0)
  page.screenshot(path=str(R/'previews/history.png'))
  fold('Branch a moment');page.click('#markMoment');page.wait_for_function('!!app.telemetry.anchor');saved=req('export')
  page.select_option('#branchVariant','wet');req('pause',value=False);page.click('#compareMoment');page.wait_for_function('!!app.job');page.wait_for_function('!app.job&&!!app.branchResult',timeout=40000);pause()
  check('Saved-moment comparison generates both physical continuations',ev('app.branchResult.cases.length===2&&app.branchResult.cases.every(c=>c.frames.length>60)'))
  check('Independent branch study does not modify its saved anchor',req('export')['anchor']==saved['anchor'])
  page.locator('#branchReport button').first.click();page.wait_for_function('!!app.replay')
  check('Counterfactual original replay uses genuine recorded frames',ev('app.replay.frames.length===app.branchResult.cases[0].frames.length'))
  page.click('#ribbonExit');worldtab();fold('Branch a moment');page.locator('#branchReport button').nth(1).click();page.wait_for_function('!!app.replay')
  check('Variant replay is separately available','WET' in page.inner_text('#ribbonText'))
  page.click('#ribbonExit');worldtab();fold('History & comparisons');page.click('#evaluate');page.wait_for_function('!!app.job');page.click('#cancelJob');check('Comparison worker can be cancelled safely',ev('!app.job'))
  pause();full=req('export');measurements['worldSaveBytes']=len(json.dumps(full,separators=(',',':')))
  check('Full save includes dynamics, traces, random states and replay codec',all(k in full['universe'] for k in ('dynamics','rng','weather','field','brains','observer')) and 'codec' in full['universe']['observer'])
  advance(300);req('import',data=full);again=req('export')
  check('Full file roundtrip restores exact physics and weather',again['universe']['dynamics']==full['universe']['dynamics'] and again['universe']['weather']==full['universe']['weather'] and again['universe']['field']==full['universe']['field'])
  check('Full file roundtrip restores both learner traces',again['universe']['brains']==full['universe']['brains'])
  check('Discovery clips survive full file import',len(again['universe']['observer']['codec']['frames'])==len(full['universe']['observer']['codec']['frames']))
  fail=ev('async()=>{try{await app.request("import",{data:{format:"wrong"}});return false}catch(e){return true}}')
  check('Invalid import is rejected atomically',fail and req('export')['universe']['dynamics']==again['universe']['dynamics'])
  awaitable=ev('async()=>{const d=await app.request("export");await app.persist(d);return document.getElementById("saveState").textContent}')
  check('Storage denial is disclosed instead of falsely claiming an autosave','unavailable' in awaitable or 'saved' in awaitable)
  fold('Save & resume')
  with page.expect_download() as download_info:page.click('#export')
  download=download_info.value;download.save_as(str(R/'reports/browser-export.json'))
  downloaded=json.loads((R/'reports/browser-export.json').read_text())
  check('Save-world button downloads a valid portable JSON file',downloaded['format']=='touchline-world-v11' and downloaded['universe']['schema']==1)
  page.set_input_files('#importFile',str(R/'reports/browser-export.json'));page.wait_for_timeout(500)
  check('UI file import resumes the world',ev('app.telemetry.roundTime>=0&&app.ready'))
  fold('Picture & performance');old=ev('app.renderer.w*app.renderer.h');page.select_option('#quality','coarse')
  check('Low-power setting lowers rendering pixels only',ev('app.renderer.w*app.renderer.h')<old)
  page.select_option('#frameLimit','30');req('pause',value=False);page.wait_for_timeout(4300);measurements['lowPower']=perf()
  check('30-fps presentation retains real-time simulation',ev('app.frameLimit===30') and .8<measurements['lowPower']['actualPace']<1.2)
  pause();page.select_option('#quality','auto');page.select_option('#frameLimit','60')
  page.select_option('#palette','day');snapshot=req('export');page.select_option('#palette','night')
  check('Manual interface palette cannot alter the physical clock',snapshot['universe']['weather']==req('export')['universe']['weather'])
  page.select_option('#palette','auto');page.click('#effects');check('Decorative weather effects can be disabled',ev('!app.renderer.fx'));page.click('#effects')
  fold('Enter the experiment');page.click('#life');page.wait_for_function('app.telemetry.life');page.select_option('#lifeMode','ecology');advance(240)
  check('Ecological cellular model is a distinct selectable system',req('export')['universe']['field']['lifeMode']=='ecology')
  page.select_option('#lifeMode','conway');check('Unmodified Conway model remains selectable',req('export')['universe']['field']['lifeMode']=='conway')
  page.click('#life');page.click('#drive');page.wait_for_function('app.telemetry.human===0');check('Player can take over Mica',ev('app.telemetry.human===0'))
  # Ten simulated seconds includes a possible 2.5-second goal pause and kickoff.
  # A two-second window can legitimately contain no learning decision.
  keyboard_before=req('export');page.focus('#arena');page.keyboard.down('w');page.keyboard.down('Shift');advance(1200);page.keyboard.up('w');page.keyboard.up('Shift');keyboard_after=req('export')
  check('Human control freezes Mica learning but not Ember',keyboard_before['universe']['brains'][0]['w']==keyboard_after['universe']['brains'][0]['w'] and keyboard_before['universe']['brains'][1]['updates']<keyboard_after['universe']['brains'][1]['updates'],{'updatesBefore':[b['updates'] for b in keyboard_before['universe']['brains']],'updatesAfter':[b['updates'] for b in keyboard_after['universe']['brains']],'goalPauseAtStart':keyboard_before['universe']['dynamics']['goalPause'],'kickoffAtStart':keyboard_before['universe']['dynamics']['kickoffTime']})
  page.click('#ribbonExit');page.wait_for_function('app.telemetry.human===-1')
  req('keys',value={'forward':True});req('hidden',value=True);state0=req('export');page.wait_for_timeout(200);state1=req('export')
  check('Hidden-document pause releases held controls',state1['universe']['dynamics']['manual']=={} and state0['universe']['dynamics']['time']==state1['universe']['dynamics']['time']);req('hidden',value=False)
  page.click('#sound');check('Procedural sound enables after a user gesture',ev('app.audio.on&&!!app.audio.surfaceAudio'));page.click('#sound');check('Sound can be muted',ev('!app.audio.on'))
  worldtab();req('weather',value={'hour':10,'mode':'clear'});page.wait_for_timeout(300);page.click('#closeInspector');page.click('[data-view="arena"]');pause();quiet()
  page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(600);page.screenshot(path=str(R/'previews/mobile.png'))
  check('Mobile viewport has no horizontal page overflow',ev('document.documentElement.scrollWidth<=innerWidth'))
  page.click('#weatherBadge');page.wait_for_timeout(300)
  check('World instruments remain usable on mobile',page.is_visible('#worldHour') and ev('document.getElementById("inspector").getBoundingClientRect().width<=innerWidth'))
  page.screenshot(path=str(R/'previews/mobile-world.png'));page.click('#closeInspector')
  page.set_viewport_size({'width':844,'height':390});page.wait_for_timeout(500)
  check('Small landscape layout has no horizontal overflow',ev('document.documentElement.scrollWidth<=innerWidth'))
  page.click('#focus');check('Focus mode removes world badge and chrome',ev('document.body.classList.contains("clean")&&getComputedStyle(document.querySelector(".weather-badge")).opacity==="0"'))
  page.click('#restoreHUD');page.set_viewport_size({'width':1440,'height':900});page.wait_for_timeout(400)
  req('weather',value={'hour':15,'mode':'clear'});advance(6000);quiet();page.screenshot(path=str(R/'previews/daylight.png'))
  req('weather',value={'hour':22,'mode':'rain'});advance(6000);quiet();page.screenshot(path=str(R/'previews/rain-night.png'))
  check('Discovery notices do not overlap the weather clock',ev('(()=>{const a=document.getElementById("notice").getBoundingClientRect(),b=document.getElementById("weatherBadge").getBoundingClientRect();return a.bottom<=b.top||a.right<=b.left||a.left>=b.right})()'))
  check('No browser JavaScript errors across all workflows',not errors,errors)
  check('No remote assets requested during any workflow',not requests)
 except Exception as e:
  check('Browser suite completed without unexpected exception',False,str(e));errors.append(traceback.format_exc());page.screenshot(path=str(R/'previews/test-failure.png'))
 finally:
  save_report();b.close()
print('RESULT',sum(x['pass'] for x in results),'passed;',sum(not x['pass'] for x in results),'failed',flush=True)
raise SystemExit(1 if errors or any(not x['pass'] for x in results) else 0)
